# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  flake,
  ...
}: {
  imports = [
    ../../modules/base-server.nix

    ../../system/services/spacebarchat
    ../../system/services/caddy.nix
    ../../system/services/cloudflared.nix
    ../../system/services/jankclient.nix
    ../../system/services/pocbot.nix
    ../../system/services/postgres.nix
    ../../system/services/vaultwarden.nix
    ../../system/services/rabbitmq.nix
  ];

  facter.reportPath = ./facter.json;

  system.autoUpgrade = {
    enable = true;
    flake = flake.outPath;
    flags = [
      "--update-input"
      "nixpkgs"
      "--update-input"
      "jankclient"
      "-L" # print build logs
    ];
    dates = "daily";
    randomizedDelaySec = "45min";
  };

  virtualisation.incus.agent.enable = true;
}
